version: 0.2
phases:
  pre_build:
    commands:
     - sudo apt-get install zip unzip
     - chmod +x gradlew
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - cp appspec.yml build
      - cp -rf scripts build  
      - cd build
      - zip -r codedeploy-$(date +%Y%m%d%H%m%S).zip *	  
artifacts:
  files:
      - /build/codedeploy-$(date +%Y%m%d%H%m%S).zip
